spring.application.name=Cogniti
spring.datasource.url=jdbc:postgresql://localhost:5432/cognito
spring.datasource.username=cognito
spring.datasource.password=veritas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
